name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: local-nix-cache
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build release.nix -A test
    - run: ./result/bin/test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.10
      with:
        source: '.'
        extensions: 'h,c,cpp,hpp'
